### ISSUE TITLE
Change path to genghisapp

### ISSUE THREAD

**Issue by thiago** [aegypius/dockerfiles#1]
Hi!
Thanks for create the [genghis](https://registry.hub.docker.com/u/aegypius/genghis/), it is a good image.

But the path of the executable script is wrong. Please, you can change `/usr/local/bin/genghisapp` for `/usr/local/bundle/bin/genghisapp` ?

Thanks!

**Comment by aegypius** [comment]
Thanks ! The latest image should be available soon.
